version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - .:/data
    networks:
      - pgnet

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - .:/data
    networks:
      - pgnet

  postgres-master:
    container_name: pgmaster
    image: postgres:latest
    ports:
      - "15432:5432"
    volumes:
      - ./postgres_master_data:/var/lib/postgresql/data
      - .:/csv_data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_REPLICATION_USER: replica
      POSTGRES_REPLICATION_PASSWORD: replica_pass
    networks:
      - pgnet

  postgres-replica:
    container_name: pgslave
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MASTER_SERVICE_HOST: postgres-master
      POSTGRES_REPLICATION_USER: replica
      POSTGRES_REPLICATION_PASSWORD: replica_pass
    ports:
      - "15433:5432"
    volumes:
      - ./postgres_replica_data:/var/lib/postgresql/data
    networks:
      - pgnet

  postgres-async-replica:
    container_name: pgasyncslave
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MASTER_SERVICE_HOST: postgres-master
      POSTGRES_REPLICATION_USER: replica
      POSTGRES_REPLICATION_PASSWORD: replica_pass
    ports:
      - "15434:5432"
    volumes:
      - ./postgres_async_replica_data:/var/lib/postgresql/data
    networks:
      - pgnet

volumes:
  postgres_master_data:
  postgres_replica_data:
  postgres_async_replica_data:

networks:
  pgnet:
    driver: bridge
